<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Calculus" data-toc-modified-id="Calculus-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Calculus</a></span><ul class="toc-item"><li><span><a href="#微分找極值" data-toc-modified-id="微分找極值-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>微分找極值</a></span></li><li><span><a href="#L’Hôpital’s-Rule" data-toc-modified-id="L’Hôpital’s-Rule-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>L’Hôpital’s Rule</a></span></li><li><span><a href="#偏微分" data-toc-modified-id="偏微分-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>偏微分</a></span></li><li><span><a href="#Chain-Rule" data-toc-modified-id="Chain-Rule-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Chain Rule</a></span></li></ul></li><li><span><a href="#Linear-Algebra" data-toc-modified-id="Linear-Algebra-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Linear Algebra</a></span><ul class="toc-item"><li><span><a href="#eigenvalue,-eigenvector" data-toc-modified-id="eigenvalue,-eigenvector-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>eigenvalue, eigenvector</a></span></li><li><span><a href="#線性方程式" data-toc-modified-id="線性方程式-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>線性方程式</a></span></li><li><span><a href="#矩陣性質" data-toc-modified-id="矩陣性質-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>矩陣性質</a></span></li><li><span><a href="#矩陣運算" data-toc-modified-id="矩陣運算-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>矩陣運算</a></span></li></ul></li><li><span><a href="#Statistics" data-toc-modified-id="Statistics-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Statistics</a></span><ul class="toc-item"><li><span><a href="#mean" data-toc-modified-id="mean-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>mean</a></span></li><li><span><a href="#median" data-toc-modified-id="median-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>median</a></span></li><li><span><a href="#mode" data-toc-modified-id="mode-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>mode</a></span></li><li><span><a href="#Range" data-toc-modified-id="Range-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Range</a></span></li><li><span><a href="#Variance-and-Standard-Deviation" data-toc-modified-id="Variance-and-Standard-Deviation-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Variance and Standard Deviation</a></span></li><li><span><a href="#coefficient-of-variation" data-toc-modified-id="coefficient-of-variation-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>coefficient of variation</a></span></li><li><span><a href="#interquartile-range" data-toc-modified-id="interquartile-range-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>interquartile range</a></span></li><li><span><a href="#機率" data-toc-modified-id="機率-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>機率</a></span></li></ul></li><li><span><a href="#Code" data-toc-modified-id="Code-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Code</a></span><ul class="toc-item"><li><span><a href="#排列組合" data-toc-modified-id="排列組合-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>排列組合</a></span></li><li><span><a href="#Fibonacci-Number" data-toc-modified-id="Fibonacci-Number-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Fibonacci Number</a></span></li><li><span><a href="#找最大值，偽代碼" data-toc-modified-id="找最大值，偽代碼-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>找最大值，偽代碼</a></span></li><li><span><a href="#palindrome，偽代碼" data-toc-modified-id="palindrome，偽代碼-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>palindrome，偽代碼</a></span></li><li><span><a href="#Fibonacci-Number-SUM，偽代碼" data-toc-modified-id="Fibonacci-Number-SUM，偽代碼-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Fibonacci Number SUM，偽代碼</a></span><ul class="toc-item"><li><span><a href="#use-Recursion" data-toc-modified-id="use-Recursion-4.5.1"><span class="toc-item-num">4.5.1&nbsp;&nbsp;</span>use Recursion</a></span></li></ul></li></ul></li></ul></div>

## Calculus

### 微分找極值
![tpe-ee1.png](https://raw.githubusercontent.com/ellickhou/Entrance-exam-of-Taiwan-AI-Academy/master/重點整理圖片/tpe-ee1.png)


- ans: 48
1. sin(bx)/x = b, sin(cx) = c
2. 化簡第一次
    - ax + b + c = 48x + 60x^3 + 72x^5
    - x -> 0, b + c = 0
3. 化簡第二次
    - sin(bx) + sin (cx) = 2sin((b+c)x/2)cos((b-c)x/2)
    - b+c = 0, sin(0) = 0
    - sin(bx) + sin (cx) = 0
4. 原本方程式變成
    - ax^2 = 48x^2 + 60x^4 + 72x^6
    - a = 48 + 60x^2 + 72x^4
    - x -> 0, a = 48
5. a= 48, b+c= 0
    - a+b+c = 48

### L’Hôpital’s Rule
![tpe-ee2.png](https://raw.githubusercontent.com/ellickhou/Entrance-exam-of-Taiwan-AI-Academy/master/重點整理圖片/tpe-ee2.png)

- L’Hôpital’s Rule
![tpe-ee2-1.png](https://raw.githubusercontent.com/ellickhou/Entrance-exam-of-Taiwan-AI-Academy/master/重點整理圖片/tpe-ee2-1.png)
- f(2+3x) + f(2+5x)/x = 3f'(2+3x) + 5f'(2+5x) /1
    - x -> 0, f'(2) = 7
    - 3 * 7 + 5 * 7 = 56 


In [1]:
import sympy
from sympy import limit, Symbol, sin, cos, oo
from sympy import *
x,a,b,c = symbols('x a b c')
diff(2+3*x)

3

### 偏微分
![tpe-ee3.png](https://raw.githubusercontent.com/ellickhou/Entrance-exam-of-Taiwan-AI-Academy/master/重點整理圖片/tpe-ee3.png)

In [2]:
import sympy
from sympy import limit, Symbol, sin, cos, oo
from sympy import *
x,y = symbols('x y')
print(diff(x**2 - y **2, x))
print(diff(x**2 - y **2, y))

2*x
-2*y


### Chain Rule
- f(x) = (2x + 1)^3
    - let g(x) = 2x+1
    - f'(x) = f'(g(x)) * g'(x)
    - = 3 * (2x + 1)^2 * (2)
    - = 6(2𝑥+1)^2
- h′(x) = df/du * du/dx
    - u = (2x + 1)
    - df/du * du/dx = 3u^2 * 2
    - = 3(2x + 1)^2 * 2 = 6(2x + 1)^2

In [3]:
from sympy import *
x, y = symbols('x y') # r (radius), t (angle theta)
f = symbols('f', cls=Function)
f = (2*x + 1)**3
Derivative(f,x, 1).doit()

6*(2*x + 1)**2

## Linear Algebra

### eigenvalue, eigenvector
![tpe-ee2.png](https://raw.githubusercontent.com/ellickhou/Entrance-exam-of-Taiwan-AI-Academy/master/重點整理圖片/tpe-ee4.png)
- (A - 入 I) X ＝ 0
- 求入，先用det，解方程式

In [4]:
import numpy as np
A = np.array([[3, 4, 2], [0, 5, 7], [0, 0, 1]])
det_ = np.linalg.det(A)
evl, evc = np.linalg.eig(A)
print(A, det_, sep = '\n')
print(evl, evc ,sep = '\n')

[[3 4 2]
 [0 5 7]
 [0 0 1]]
15.0
[3. 5. 1.]
[[ 1.          0.89442719  0.77849894]
 [ 0.          0.4472136  -0.54494926]
 [ 0.          0.          0.31139958]]


### 線性方程式
![tpe-ee5.png](https://raw.githubusercontent.com/ellickhou/Entrance-exam-of-Taiwan-AI-Academy/master/重點整理圖片/tpe-ee5.png)

- 帶入法硬解，記得開根號

### 矩陣性質
![tpe-ee6.png](https://raw.githubusercontent.com/ellickhou/Entrance-exam-of-Taiwan-AI-Academy/master/重點整理圖片/tpe-ee6.png)

- 正交，內積為0，線性獨立

In [5]:
import numpy as np
A = np.array([[4, 2, 0, 0], [2, 4, 0,0], [0, 0, 4, 2], [0,0,2,4]])
# 行列式
det_ = np.linalg.det(A)
# eigenvalue, eigenvector
evl, evc = np.linalg.eig(A)
print(A, det_, sep = '\n')
print(evl, evc ,sep = '\n')

[[4 2 0 0]
 [2 4 0 0]
 [0 0 4 2]
 [0 0 2 4]]
144.0
[6. 2. 6. 2.]
[[ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          0.70710678 -0.70710678]
 [ 0.          0.          0.70710678  0.70710678]]


### 矩陣運算

In [6]:
A = np.array([[1,3],
                   [2,4]])
B = np.array([[1,3],
                   [2,4]])
#內積
dotAB = A.dot(B)
C = np.mat('1,2,3; \
                 5,5,5 ; \
                 7,8,9 ')
#反矩陣
revC = C.I
#轉置矩陣
tranA = A.T

# 相似矩陣
#T_similar = P*T*P.I

## Statistics

### mean
- sample mean of a set of n sample data
    - mean_x = sum(x)/n
-  population mean of a set of N population data
    - μ =  sum(x)/n

###  median
- For a set has odd number of sample data:
    - The middle sample data
- For a set has even number of sample data:
    - The mean of the tow middle sample data

### mode
- the value that appears most often

In [7]:
import statistics as stat
ds = []
a1 = stat.mean(ds)
a2 = stat.median(ds)
a3 = stat.mode(ds)
print(a1, a2, a3, sep = ';')

StatisticsError: mean requires at least one data point

### Range
- R = max(x) - min(x)

In [ ]:
ds = [1, 2]
R = max(ds) - min (ds)
print(R)

### Variance and Standard Deviation
![tpe-ee7.png](https://raw.githubusercontent.com/ellickhou/Entrance-exam-of-Taiwan-AI-Academy/master/重點整理圖片/tpe-ee7.png)

In [8]:
import statistics as stat
ds = [1,2,3]
#Sample variance of data.
a1 = stat.variance(ds)
#Sample standard deviation of data.
a2 = stat.stdev(ds)
#Population variance of data.
a3 = stat.pvariance(ds)
#Population standard deviation of data.
a4 = stat.pstdev(ds)
print('variance = %s' %a1 , 'stdev = %s' %a2
      , 'pvariance = %s' %a3, 'pstdev = %s' %a4, sep = ' ; ')

variance = 1 ; stdev = 1.0 ; pvariance = 0.6666666666666666 ; pstdev = 0.816496580927726


### coefficient of variation

In [9]:
import scipy.stats
import numpy as np
ds = np.array([1,2,3,4,5])
scipy.stats.variation(ds)

0.47140452079103173

### interquartile range
- Q3 - Q1

### 機率
![tpe-ee9.png](https://raw.githubusercontent.com/ellickhou/Entrance-exam-of-Taiwan-AI-Academy/master/重點整理圖片/tpe-ee9.png)


- 獨立事件
    - A交集B = ＰＡ ＊ ＰＢ
    - 

## Code

### 排列組合
![tpe-ee11.png](https://raw.githubusercontent.com/ellickhou/Entrance-exam-of-Taiwan-AI-Academy/master/重點整理圖片/tpe-ee11.png)
- ans: E

In [10]:
ds = [1,3,5,7,9,8,6,4,2]
print(len(ds))
for i in range(0, len(ds)):
    temp = ds[i]
    ds[i] = ds[len(ds)-i-1]
    ds[len(ds)-i-1] = ds[i]
print(ds)

for j in range(0,int(len(ds)/2)):
    print(ds[j], ds[len(ds)-j-1])

9
[2, 4, 6, 8, 9, 8, 6, 4, 2]
2 2
4 4
6 6
8 8


### Fibonacci Number
![tpe-ee12.png](https://raw.githubusercontent.com/ellickhou/Entrance-exam-of-Taiwan-AI-Academy/master/重點整理圖片/tpe-ee12.png)

- ans: C

In [11]:
a=0
b=1
N=5
temp= 0
for i in range(2,N+1):
    temp = b
    b = a+b
    a = temp
    print(b)

1
2
3
5


### 找最大值，偽代碼

    func find_max(L) -> max_:
        # L <- a list
        # max_ <- int
        max_ <- L[0]
        for i in L do
            if i > max_ then
                    max_ <- i
        return max

In [12]:
def find_max(L):
    # L <- a array
    # max <- array
    max1 = L[0]
    max2 = L[0]
    max3 = L[0]
    for i in L:
        if i > max1:
            max1 = i
    L[L.index(max1)] = 0
    for j in L:
        if j >max2:
            max2 = j
    L[L.index(max2)] = 0
    for k in L:
        if k > max3:
            max3 = k
    array= [max3, max2, max1]
    return array

ds = [0,9,10,132,88, 10,88,3,4,-100]
find_max(ds)

[88, 88, 132]

### palindrome，偽代碼

    func if_palindrome(x) -> y:
        # x <- int
        # y <- bool
        y <- None
        if x < 0 then
            y <- False
            return y
        end if
        re_x <- 0
        temp <- x
        while temp >= 1 do
           re_x <- re_x*10 + (temp 除10的餘數)
           temp <- temp 除10的整數商
       end for
       if x == re_x then
           y = True
       else then
           y = False
       end if
       return y


In [13]:
def if_palindrome(x):
    # x <- int
    # y <- bool
    y = None
    if x < 0:
        y = False
        return y
    re_x = 0
    temp = x
    while temp >= 1:
        re_x = re_x*10 + temp %10
        temp = temp // 10
    if x == re_x:
        y = True
    else :
        y = False
    print(x, re_x)
    return y

if_palindrome(1231)

1231 1321


False

### Fibonacci Number SUM，偽代碼
- Hint: try not to use Recursion
    - x = x + 10

    func fib(N) -> Sum :
        # N <- int, N >=2
        # Sum <- int
        fib_seq <- an list contain[0,1]
        for (i = 2 to i = N) do:
            fib_seq append ( fib_seq[i-1] + fib_seq [i - 2] )
        end for
        Sum <- sum of all element in fib_seq
        return sum

In [14]:
def fib(N):
    # N <- int, >=2
    # Sum <- int
    fib_seq = [0,1]
    for i in range(2,N+1):
        fib_seq.append( fib_seq[i-1] + fib_seq [i - 2] )
    Sum = sum(fib_seq)
    return fib_seq, Sum

fib(5)

([0, 1, 1, 2, 3, 5], 12)

####  use Recursion


    func fib(N) -> Sum :
        # N <- int, N >=2
        # Sum <- int
        a <- 0
        b <- 1
        temp <- 0
        Sum <- 0
        for (i = 0 to i = N) do:
            temp <- b
            b <- a + b
            a <- temp
            Sum = Sum + a
        end for
        return Sum

In [15]:
def fib(N):
    # N <- int, N >=2
    # Sum <- int
    a=0
    b=1
    temp=0
    Sum = 0
    for i in range(0, N):
        temp = b
        b = a + b
        a = temp
        Sum = Sum + a
        
    return a,Sum
fib(3)

(2, 4)

In [16]:
a = [1,3,9,2,5,8,4,9,6,7]
index = 0
for i in range(len(a)):
    if a[i] > a[index]:
        index = i
index

2

In [17]:
def function(n):
    fac = 1
    if n > 0:
        fac = n* function(n-1)
    return fac
function(4)

24

In [18]:
A = np.array([[1,1],[1,0]])
F = np.array([[1],[0]])
dotA2 = A.dot(A)
dotA3 = dotA2.dot(A)
dotA4 = dotA3.dot(A)
dotA5 = dotA4.dot(A)
dotA6 = dotA5.dot(A)
dotA7 = dotA6.dot(A)
dotA8 = dotA7.dot(A)
dotA8F = dotA8.dot(F)
print(dotA8F)

[[34]
 [21]]


In [19]:
a = 3600.7*19 - 4120 + 4210
b = a /19
print(a,b)

68503.3 3605.436842105263


In [20]:
a = 3600.7*19 - 4120 + 4210
s2 = 14655
old = 14655 * 18 + ((3600.7*19)**2/19)
Ns2 = ((old - 4120**2 + 4210**2) - a**2/19) /18
Ns2

20274.31578947438